target 'mach1-decode-example' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'Mach1SpatialAPI', :path => '../../'
end
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
