# Uncomment the next line to define a global platform for your project
 platform :ios, '9.3'

target 'mach1-navigation-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navigation
  pod 'Mach1SpatialAPI', '~> 0.1'

end
